Metatavu/metaform-management-portal

package.json
=> Added new name

package-lock.json, package.json, src/app/config.ts, src/components/contexts/error-handler.tsx, src/index.tsx
=> Added sentry

src/utils/metaform-utils.ts
=> Feature 11 editor basic utilities

src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformHtmlComponent.tsx, src/styled/react-components/react-components.ts
=> Translated html field to MUI functional component

src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformHtmlComponent.tsx, src/metaform-react/MetaformTextFieldComponent.tsx, src/metaform-react/MetaformUrlField.tsx, src/styled/generic/form.ts, src/styled/react-components/react-components.ts
=> Rewrited field components and added styling

src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformHtmlComponent.tsx, src/metaform-react/MetaformNumberFieldComponent.tsx, src/metaform-react/MetaformRadioFieldComponent.tsx, src/metaform-react/MetaformSelectFieldComponent.tsx, src/styled/react-components/react-components.ts
=> Feature 38 translate more fields

.gitignore, package-lock.json, src/components/generic/form.tsx, src/metaform-react/MetaformMemoComponent.tsx
=> Translated memo to functional component

src/metaform-react/MetaformHiddenFieldComponent.tsx
=> Translated hidden

src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/metaform-react/MetaformHiddenFieldComponent.tsx
=> Feature 33 translate files field

src/metaform-react/MetaformEmailComponent.tsx
=> Translated email field

src/metaform-react/MetaformDateTimeFieldComponent.tsx, src/metaform-react/MetaformEmailComponent.tsx, src/metaform-react/MetaformFieldComponent.tsx
=> Feature 31 translate date time

src/metaform-react/MetaformDateFieldComponent.tsx, src/metaform-react/MetaformFieldComponent.tsx
=> Translated date

src/metaform-react/MetaformBooleanFieldComponent.tsx
=> Translated boolean

src/metaform-react/MetaformSectionComponent.tsx
=> Translated section

src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/metaform-react/MetaformTableFieldComponent.tsx, src/styled/react-components/react-components.ts
=> Translated table field

src/components/generic/form.tsx, src/metaform-react/MetaformBooleanFieldComponent.tsx, src/metaform-react/MetaformComponent.tsx, src/metaform-react/MetaformDateFieldComponent.tsx, src/metaform-react/MetaformDateTimeFieldComponent.tsx, src/metaform-react/MetaformEmailComponent.tsx, src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/metaform-react/MetaformHiddenFieldComponent.tsx, src/metaform-react/MetaformMemoComponent.tsx, src/metaform-react/MetaformSectionComponent.tsx
=> Feature 44 translate metaform component

src/components/screens/forms/form-screen.tsx, src/components/screens/forms/form/Autosaving.tsx, src/components/screens/forms/form/DraftSaveDialog.tsx, src/components/screens/forms/form/DraftSavedDialog.tsx, src/components/screens/forms/form/ReplyDelete.tsx, src/components/screens/forms/form/ReplyEmailDialog.tsx, src/components/screens/forms/form/ReplySaved.tsx
=> Feature 65 split form screen

src/components/screens/forms/forms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styled/react-components/react-components.ts
=> Feature 70 Administrator form list

src/api/index.ts, src/app/config.ts, src/app/hooks.ts, src/components/screens/forms/form-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/metaform-utils.ts
=> Added API connection

src/components/layouts/breadcrumbs/form-breadcrumb.tsx, src/components/layouts/breadcrumbs/routes.ts, src/components/screens/forms/form-answer-screen.tsx, src/components/screens/forms/forms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styled/react-components/react-components.ts
=> Feature 75 Form Replies/Answer Screen

src/components/generic/form.tsx, src/components/screens/forms/form-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Feature 76 form screen api calls

src/components/generic/form.tsx, src/components/screens/forms/form-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/metaform-react/MetaformComponent.tsx, src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/metaform-react/MetaformSectionComponent.tsx
=> Feature 79 form tsx eslint

src/components/editor/field-renderer/addable-field-renderer.tsx, src/components/generic/tab-panel.tsx, src/metaform-react/MetaformBooleanFieldComponent.tsx, src/metaform-react/MetaformChecklistFieldComponent.tsx, src/metaform-react/MetaformEmailComponent.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/metaform-react/MetaformHtmlComponent.tsx, src/metaform-react/MetaformMemoComponent.tsx, src/metaform-react/MetaformNumberFieldComponent.tsx, src/metaform-react/MetaformRadioFieldComponent.tsx, src/metaform-react/MetaformSelectFieldComponent.tsx, src/metaform-react/MetaformSliderFieldComponent.tsx, src/metaform-react/MetaformSubmitFieldComponent.tsx, src/metaform-react/MetaformTableFieldComponent.tsx, src/metaform-react/MetaformUrlField.tsx
=> Feature 86 addable field bugs

src/components/App.tsx, src/components/containers/access-token-refresh.tsx
=> Admin authentication

package-lock.json, src/components/editor/field-renderer/addable-field-renderer.tsx, src/components/layout-components/header.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/metaform-react/MetaformComponent.tsx, src/metaform-react/MetaformDateFieldComponent.tsx, src/metaform-react/MetaformDateTimeFieldComponent.tsx, src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/metaform-react/MetaformMemoComponent.tsx, src/metaform-react/MetaformSectionComponent.tsx, src/metaform-react/MetaformSelectFieldComponent.tsx, src/metaform-react/MetaformSubmitFieldComponent.tsx, src/metaform-react/MetaformTableFieldComponent.tsx, src/styled/generic/form.ts, src/styled/layouts/public-layout.ts, src/styled/react-components/react-components.ts, src/theme/index.ts
=> Feature 98 form and component styles

src/components/generic/generic-loader.tsx, src/components/screens/users/users-screen.tsx, src/components/users/add-member-dialog.tsx, src/components/users/add-member-group-dialog.tsx, src/components/users/users-filter.tsx, src/components/users/users-table.tsx
=> Added generic loader and implemented it on users screen

src/metaform-react/MetaformChecklistFieldComponent.tsx
Resolves https://github.com/Metatavu/essote-management-portal/issues/119
=> Checkbox checkable by clicking its label

src/components/App.tsx, src/components/editor/editor-screen-drawer.tsx, src/components/editor/metaform-editor-left-drawer.tsx, src/components/editor/metaform-editor.tsx, src/components/generic/tab-panel.tsx, src/components/screens/editor/draft-editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/index.ts, src/utils/metaform-utils.ts, src/utils/sosmeta-utils.ts
Contains: 
- Resolve of #126 
- Minor changes to draft-editor.screen to better support the functionality of this feature
=> Feature 126 sosmeta converter

src/components/editor/editor-screen-drawer.tsx
Resolves #134 
Also centered loader in drawer when converting sosmeta schema to metaform
=> Form visiblity changeable when creating new form

src/components/editor/editor-screen-table.tsx, src/components/generic/generic-loader.tsx, src/components/screens/editor/draft-editor-screen.tsx, src/components/screens/editor/editor-screen.tsx, src/components/screens/forms/form-replies-screen.tsx, src/components/screens/forms/form-reply-screen.tsx, src/components/screens/forms/forms-data-screen.tsx, src/components/screens/forms/forms-screen.tsx, src/components/users/users-table.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styled/editor/metaform-editor.tsx, src/styled/layouts/navigations.ts
=> Feature 137 single reply status

src/components/editor/editor-screen-table.tsx
=> Form delete click fixed

src/components/editor/editor-screen-table.tsx, src/components/screens/editor/draft-editor-screen.tsx, src/components/screens/editor/editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Edit and publish form workflow

src/app/store.ts, src/components/App.tsx, src/components/layout-components/header.tsx, src/components/screens/editor/draft-editor-screen.tsx, src/components/screens/editor/editor-screen.tsx, src/features/locale-slice.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styled/layout-components/header.ts
Closes #145 and fixes code smell leftovers from earlier commit that was rushed for demo :)
=> Feature 145 localization change

src/components/editor/field-renderer/addable-field-renderer.tsx, src/components/generic/form.tsx, src/metaform-react/MetaformBooleanFieldComponent.tsx, src/metaform-react/MetaformChecklistFieldComponent.tsx, src/metaform-react/MetaformEmailComponent.tsx, src/metaform-react/MetaformFieldComponent.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/metaform-react/MetaformHtmlComponent.tsx, src/metaform-react/MetaformMemoComponent.tsx, src/metaform-react/MetaformRadioFieldComponent.tsx, src/metaform-react/MetaformSelectFieldComponent.tsx, src/metaform-react/MetaformSliderFieldComponent.tsx, src/metaform-react/MetaformTableFieldComponent.tsx, src/metaform-react/MetaformTextFieldComponent.tsx, src/metaform-react/MetaformUrlField.tsx, src/styled/react-components/react-components.ts
=> Feature 149 improve react form element accessibility

src/components/screens/public/public-forms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> home screen if user get lost

src/components/editor/metaform-editor-left-drawer.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Show url and edit slug when u edit title
=> Show url and edit slug when u edit title

src/components/contexts/connection-handler.tsx, src/components/contexts/error-handler.tsx, src/components/contexts/leave-page-handler.tsx, src/components/generic/generic-snackbar.tsx, src/components/screens/forms/form-screen.tsx, src/components/screens/forms/form/DraftSavedDialog.tsx, src/components/screens/forms/form/ReplySaved.tsx, src/components/screens/public/public-routes.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Resolves #147 and also adds Generic Snackbar component
=> Feature 147 refine error handling and usability

src/components/editor/field-renderer/addable-field-renderer.tsx, src/components/editor/metaform-editor-left-drawer.tsx, src/components/editor/metaform-editor-right-drawer-feature.tsx, src/components/editor/metaform-editor-right-drawer-visibility.tsx, src/components/editor/metaform-editor-right-drawer.tsx, src/components/editor/metaform-editor.tsx, src/components/screens/public/public-forms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/metaform-utils.ts
Added options to select/checkbox/radio fields and some table features.
=> Feature 148 editor add option to adddeleteedit selectradio choices

src/api/index.ts, src/components/screens/forms/forms-data-screen.tsx, src/components/screens/forms/forms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/index.ts, src/utils/metaform-utils.ts
=> Feature 162 forms data view

src/api/index.ts, src/components/generic/form-autocomplete.tsx, src/components/screens/forms/form-history-screen.tsx, src/components/screens/forms/form-replies-screen.tsx, src/components/screens/forms/forms-data-screen.tsx, src/components/screens/forms/forms-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styled/react-components/react-components.ts, src/utils/localization-utils.ts
=> Feature 167 form history screen

src/components/editor/editor-screen-table.tsx, src/components/screens/editor/draft-editor-screen.tsx, src/components/screens/editor/editor-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/data-validation-utils.ts
Resolves #171 
Also adds confirmation dialog for when publishing draft form.
Also minor bugfix related to navigating to draft editor when draft has different slug than corresponding Metaform
=> Feature 171 Update form versions

src/components/editor/editor-screen-table.tsx, src/components/screens/forms/forms-data-screen.tsx
=> Metaforms metadata

src/localization/en.json, src/localization/fi.json
=> Renamed reply auditlog types strings.

src/components/screens/editor/editor-screen.tsx
=> Fixed new versions creation bug

src/components/editor/metaform-editor-left-drawer.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
Form visibility changing option.
=> Feature to change form visibility

src/components/editor/metaform-editor-left-drawer.tsx, src/components/editor/metaform-editor-right-drawer-feature.tsx
=> fixed loss focus

src/components/screens/preview/draft-preview-screen.tsx
=> Changed url of the shared link, removed slug check

src/components/screens/forms/form-screen.tsx, src/components/screens/forms/forms-screen.tsx
-Not adding the form screen debounce until after customer testing.
=> Feature 205 refining UI

src/components/editor/metaform-editor-left-drawer.tsx, src/components/editor/metaform-editor-right-drawer-feature.tsx, src/components/editor/metaform-editor-right-drawer.tsx, src/components/editor/metaform-editor.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/index.ts, src/utils/metaform-utils.ts
Permission member groups for form
=> User can add permission member groups

src/components/editor/metaform-editor-right-drawer-feature.tsx, src/components/editor/metaform-editor-right-drawer-visibility.tsx, src/metaform-react/MetaformNumberFieldComponent.tsx, src/metaform-react/MetaformSliderFieldComponent.tsx, src/utils/metaform-utils.ts
Slider marks and number min max values
=> Slider marks and number min max values

src/utils/sosmeta-utils.ts
-Empty sections removed and missing henkilötunnus fields now translated
=> Feature 211 refine sosmeta translation

src/components/editor/metaform-editor-right-drawer-feature.tsx, src/types/index.ts, src/utils/metaform-utils.ts
=> fixed permission group selection and code refining

src/components/containers/authentication-provider.tsx
=> changed interval

src/app/config.ts
=> Feature 235 add infolink button in header

src/components/editor/metaform-editor-right-drawer-visibility.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/metaform-react/VisibleIfEvaluator.ts
Or visibleif condition and and
=> Possibility to have more visibleIf conditions

src/components/generic/form.tsx
=> Disabled past dates and current date from the date and datetime pickers

src/api/index.ts, src/components/screens/editor/editor-screen.tsx
=> Added email template when creating new form

src/components/editor/feature-components/MetaformContextOptionsComponent.tsx, src/components/editor/feature-components/MetaformDateTimeComponent.tsx, src/components/editor/feature-components/MetaformDefineMemberGroupComponent.tsx, src/components/editor/feature-components/MetaformFieldAndSubmitTitleEditComponent.tsx, src/components/editor/feature-components/MetaformFieldRequiredComponent.tsx, src/components/editor/feature-components/MetaformMultiChoiceFieldPropertiesComponent.tsx, src/components/editor/feature-components/MetaformSlidercomponent.tsx, src/components/editor/feature-components/MetaformTableComponent.tsx, src/components/editor/metaform-editor-right-drawer-feature.tsx, src/components/editor/metaform-editor-right-drawer-visibility.tsx, src/components/editor/metaform-editor-right-drawer.tsx, src/components/editor/metaform-editor.tsx, src/components/generic/form.tsx, src/components/layout-components/header.tsx, src/components/screens/editor/draft-editor-screen.tsx, src/components/screens/forms/forms-screen.tsx, src/features/metaform-slice.ts, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/metaform-react/MetaformFilesFieldComponent.tsx, src/utils/metaform-utils.ts
Smaller components for feature
=> Feature components

src/app/config.ts, src/app/hooks.ts, src/components/containers/authentication-provider.tsx, src/components/screens/public/protected-form-screen.tsx, src/features/auth-slice.ts
=> Fixes issue #280

src/components/preview/draft-preview-dialog.tsx, src/components/screens/preview/draft-preview-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Added title and link to email subject and content

src/components/editor/field-renderer/addable-field-renderer.tsx, src/components/generic/form.tsx
=> Fixed datepicker labels

src/components/users/edit-member-dialog.tsx
Resolves #294 
- Also prevent link switch from resetting.
=> Linking user now  changes username

src/components/contexts/connection-handler.tsx, src/components/editor/feature-components/MetaformFieldAndSubmitTitleEditComponent.tsx, src/components/editor/feature-components/MetaformMultiChoiceFieldPropertiesComponent.tsx, src/components/editor/feature-components/MetaformTableComponent.tsx, src/components/editor/metaform-editor.tsx, src/components/generic/generic-snackbar.tsx, src/components/layouts/admin-layout.tsx, src/components/screens/forms/form/ReplySaved.tsx, src/components/screens/public/public-form-screen.tsx, src/localization/fi.json, src/theme/index.ts, src/utils/metaform-utils.ts, src/utils/sosmeta-utils.ts
=> Feature 303 UI refining

src/components/screens/forms/form-reply-screen.tsx, src/metaform-react/MetaformFilesFieldComponent.tsx, src/utils/metaform-utils.ts
=> Fixed attachment logic

src/components/screens/public/public-welcome-screen.tsx, src/localization/fi.json, src/styled/react-components/react-components.ts, src/theme/index.ts
=> Feature 308 UI mobile optimization

package-lock.json, package.json, public/index.html, src/app/config.ts, src/components/App.tsx, src/components/layout-components/header.tsx, src/components/layouts/navigations/navigation-link.tsx, src/components/preview/draft-preview-header.tsx, src/styled/generic/form.ts, src/styled/layout-components/header.ts, src/styled/layouts/basic-layout.ts, src/styled/react-components/react-components.ts, src/theme/index.ts, src/types/index.ts, src/utils/theme-utils.ts
Resolves #312 
Requires additional envs for testing.
=> Feature 312 support for theming envs

src/components/contexts/error-handler.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts
=> Error message adjustments

src/components/screens/forms/form-replies-screen.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/utils/file-utils.ts
=> Feature 320 excel export

src/utils/metaform-utils.ts
=> bugfix 327 creating a new field on empty form causes infinite loop

src/utils/metaform-utils.ts
=> Hotfix: Fixed unique name check to prevent loop when adding new field

src/utils/metaform-utils.ts
=> Hotfix: Added unique name for submit field

src/components/form-editor/feature-components/MetaformScriptsComponent.tsx, src/components/form-editor/metaform-editor-left-drawer.tsx
=> Publishing bug fixed

src/components/screens/forms/form-replies-screen.tsx, src/utils/script-utils.ts
=> Chrome support

src/components/containers/feature.tsx, src/components/form-editor/metaform-editor-right-drawer-feature.tsx, src/components/screens/users/users-screen.tsx, src/components/users/add-member-dialog.tsx, src/components/users/card-auth-feature-add-member-dialog.tsx, src/components/users/card-auth-feature-edit-member-dialog.tsx, src/components/users/edit-member-dialog.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/types/index.ts
=> Featurized add group member and edit group member dialogs

src/app/config.ts, src/components/containers/feature.tsx, src/components/form-editor/editor-screen-drawer.tsx, src/components/form-editor/feature-components/MetaformContextOptionsComponent.tsx, src/components/form-editor/feature-components/MetaformDefineMemberGroupComponent.tsx, src/components/form-editor/feature-components/MetaformFieldClassifiersComponent.tsx, src/components/form-editor/feature-components/MetaformMultiChoiceFieldPropertiesComponent.tsx, src/components/form-editor/feature-components/MetaformScriptsComponent.tsx, src/components/form-editor/feature-components/MetaformTableComponent.tsx, src/components/form-editor/metaform-editor-left-drawer.tsx, src/components/form-editor/metaform-editor-right-drawer-feature.tsx, src/components/form-editor/metaform-editor-right-drawer-visibility.tsx, src/components/form-editor/metaform-editor-right-drawer.tsx, src/components/layout-components/header.tsx, src/components/layouts/navigations/navigation-link.tsx, src/components/screens/forms/form-replies-screen.tsx, src/components/users/add-member-dialog.tsx, src/components/users/add-member-group-dialog.tsx, src/components/users/card-auth-feature-add-member-dialog.tsx, src/components/users/card-auth-feature-edit-member-dialog.tsx, src/components/users/edit-member-dialog.tsx, src/components/users/users-screen-dialog.tsx, src/localization/en.json, src/localization/fi.json, src/localization/strings.ts, src/styled/editor/metaform-editor.tsx, src/styled/react-components/react-components.ts, src/theme/index.ts, src/types/index.ts
=> Feature 340 UI finetuning

generator-config.json, open-api/typescript-client/apis.mustache, open-api/typescript-client/modelOneOf.mustache, src/app/config.ts, src/components/screens/editor/editor-screen.tsx, src/components/screens/forms/form-replies-screen.tsx, src/types/index.ts
=> Feature 358 improved replies listing

public/index.html, src/app/config.ts
=> Removed google fonts

src/components/screens/public/public-form-screen.tsx
=> Fix error handling when saving reply
